"""Map build labels to PE versions and generate PyInstaller VERSIONINFO."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import re
import struct
import unicodedata
from pathlib import Path


APPROVED_STRINGS = {
    "ProductName": "DOCSight",
    "FileDescription": "DOCSight Desktop Preview",
    "CompanyName": "DOCSight Project",
    "LegalCopyright": "Copyright (c) 2026 Dennis Braun",
    "OriginalFilename": "DOCSight.exe",
}

_DATE_LABEL = re.compile(
    r"^v(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})\."
    r"(?P<sequence>\d+)(?P<suffix>-.+)?$"
)
_HASH_NAMESPACE = b"DOCSight PE file version v1\x00"
_MAX_LABEL_UTF16_UNITS = 4096


def validate_label(label: str) -> str:
    """Return an unchanged label after validating it for a VERSIONINFO string."""
    if not isinstance(label, str):
        raise TypeError("build label must be a string")
    if not label or not label.strip():
        raise ValueError("build label must not be empty or whitespace-only")
    if len(label.encode("utf-16-le", errors="surrogatepass")) // 2 > _MAX_LABEL_UTF16_UNITS:
        raise ValueError(
            f"build label exceeds {_MAX_LABEL_UTF16_UNITS} UTF-16 code units"
        )

    for character in label:
        codepoint = ord(character)
        category = unicodedata.category(character)
        is_noncharacter = (
            0xFDD0 <= codepoint <= 0xFDEF
            or codepoint & 0xFFFF in {0xFFFE, 0xFFFF}
        )
        if category in {"Cc", "Cs"} or is_noncharacter:
            raise ValueError("build label contains an invalid control character")

    return label


def _label_digest(label: str) -> bytes:
    return hashlib.sha256(_HASH_NAMESPACE + label.encode("utf-8")).digest()


def _valid_date_components(match: re.Match[str]) -> tuple[int, int, int] | None:
    components = tuple(
        int(match.group(name)) for name in ("year", "month", "day")
    )
    try:
        dt.date(*components)
    except ValueError:
        return None
    return components


def map_file_version(label: str) -> tuple[int, int, int, int]:
    """Map a human build label to a deterministic four-part PE file version."""
    label = validate_label(label)
    match = _DATE_LABEL.fullmatch(label)
    if match is not None:
        date_components = _valid_date_components(match)
        sequence = int(match.group("sequence"))
        suffix = match.group("suffix")
        if date_components is not None and suffix is None and sequence <= 65535:
            return (*date_components, sequence)
        if date_components is not None and suffix is not None:
            suffix_component = int.from_bytes(_label_digest(label)[:2], "big")
            return (*date_components, suffix_component)

    return struct.unpack(">4H", _label_digest(label)[:8])


def file_version_string(label: str) -> str:
    return ".".join(str(component) for component in map_file_version(label))


def version_strings(label: str) -> dict[str, str]:
    """Return the complete string table expected in the executable."""
    label = validate_label(label)
    return {
        **APPROVED_STRINGS,
        "FileVersion": file_version_string(label),
        "ProductVersion": label,
    }


def render_version_info(label: str) -> str:
    """Render a deterministic PyInstaller VERSIONINFO resource definition."""
    numeric_version = map_file_version(label)
    string_structs = "\n".join(
        f"        StringStruct({key!r}, {value!r}),"
        for key, value in version_strings(label).items()
    )
    return f"""# Generated by packaging/windows/pe_version.py; do not edit.
VSVersionInfo(
  ffi=VSFixedFileInfo(
    filevers={numeric_version!r},
    prodvers={numeric_version!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
{string_structs}
        ],
      ),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def write_version_info(output: Path, label: str) -> None:
    rendered = render_version_info(label)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate deterministic DOCSight PE version metadata."
    )
    parser.add_argument("--label", required=True, help="Human product version label")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args(argv)

    try:
        write_version_info(args.output, args.label)
    except (TypeError, ValueError) as exc:
        parser.error(str(exc))

    print(
        "Generated PE version metadata: "
        f"ProductVersion={args.label!r}, FileVersion={file_version_string(args.label)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
